NotepadMVC/Models/ProfilePhotoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NotepadMVC.Models
{
    public class ProfilePhotoViewModel
    {
        public bool Uploaded { get; set; }
        public string Photo { get; set; }
    }
}

NotepadMVC/Controllers/ProfilePhotoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NotepadMVC.Data;
using NotepadMVC.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace NotepadMVC.Controllers
{ //https://docs.microsoft.com/tr-tr/aspnet/core/mvc/models/file-uploads?view=aspnetcore-5.0
    [Authorize]
    public class ProfilePhotoController : Controller
    {
        private readonly IWebHostEnvironment env;
        private readonly ApplicationDbContext db;

        public ProfilePhotoController(IWebHostEnvironment env, ApplicationDbContext db)
        {
            this.env = env;
            this.db = db;
        }
        public IActionResult Index(string result)
        {
            var vm = new ProfilePhotoViewModel()
            {
                Uploaded = result == "Successfuly uploaded",
                Photo = db.Users.Find(User.FindFirstValue(ClaimTypes.NameIdentifier)).Photo

            };
            return View(vm);
        }
        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Index(IFormFile photo)
        {
            if (photo == null || photo.Length == 0)
            {
                ModelState.AddModelError("photo", " Please select image file fisrt.");
            }
            else if (!photo.ContentType.StartsWith("image/"))
            {
                ModelState.AddModelError("photo", "Wrong type of file! , Please select image file.");
            }
            //izin verilen en büyük dosya boyutu 1MB
            else if (photo.Length > 1 * 1000 * 1000)
            {
                ModelState.AddModelError("photo", "Maximum file size 1MB! , Please choose image size under 1MB.");

            }
            if (ModelState.IsValid)
            {
                string uzanti = Path.GetExtension(photo.FileName);
                string newFileName = Guid.NewGuid() + uzanti;
                string filePath = Path.Combine(env.WebRootPath, "uploads", newFileName);
                using (var fs = System.IO.File.Create(filePath))
                {
                    photo.CopyTo(fs);
                }
                ApplicationUser user = db.Users.Find(User.FindFirstValue(ClaimTypes.NameIdentifier));
                DeletePhotoFile(user.Photo);
                user.Photo = newFileName;
                db.SaveChanges();
                return RedirectToAction("Index", new { result = "Successfuly uploaded" });
            }
            var vm = new ProfilePhotoViewModel()
            {
                Photo = db.Users.Find(User.FindFirstValue(ClaimTypes.NameIdentifier)).Photo

            };
            return View(vm);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult DeletePhoto()
        {
            ApplicationUser user = db.Users.Find(User.FindFirstValue(ClaimTypes.NameIdentifier));
            DeletePhotoFile(user.Photo);
            user.Photo = null;
            db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        private void DeletePhotoFile(string fileName)
        {
            if (!string.IsNullOrEmpty(fileName))
            {
                var photoPath = Path.Combine(env.WebRootPath, "uploads", fileName);
                if (System.IO.File.Exists(photoPath))
                {
                    System.IO.File.Delete(photoPath);
                }
            }
        }
    }
}

NotepadMVC/Views/ProfilePhoto/Index.cshtml
@model ProfilePhotoViewModel
@{
    ViewData["Title"] = "Profile Photo";
}
<h1>Profile Photo</h1>

@if (Model.Uploaded)
{
    <div class="alert alert-success">
        Selected image is successfully loaded.
    </div>
}

<div class="d-flex">
    <div class="text-center">
            <vc:profile-photo width1="200" height1="200" class1=""/>
        @if (!string.IsNullOrEmpty(Model.Photo))
        {
            <form asp-controller="ProfilePhoto" asp-action="DeletePhoto" method="post">
                <button class="btn btn-link">Delete Photo</button>
            </form>
        }

    </div>

    <form method="post" class="p-5" enctype="multipart/form-data">
        <label for="photo">Adding Photo :</label> <br />
        <input type="file" accept="image/*" name="photo" id="photo" />
        <button class="btn btn-outline-primary">Add Photo</button>
        <div class="text-danger">
            @Html.ValidationMessage("photo")
        </div>
    </form>

</div>