NotepadMVC/Models/NoteViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NotepadMVC.Models
{
    public class NoteViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
    }
}

NotepadMVC/Controllers/NotesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NotepadMVC.Data;
using NotepadMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace NotepadMVC.Controllers
{
    [Authorize] //giriş yapıldıgını kontrol eder
    public class NotesController : Controller
    {
        private readonly ApplicationDbContext db;

        public NotesController(ApplicationDbContext db)
        {
            this.db = db;
        }
        public IActionResult Yeni()
        {
            return View();
        }
        [HttpPost,ValidateAntiForgeryToken]
        public IActionResult Yeni(Note note)
        {
            if (ModelState.IsValid)
            {
                note.AuthorId = User.FindFirst(ClaimTypes.NameIdentifier).Value; // Kimin giriş yaptıgını söyler ki
                db.Notes.Add(note);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        public IActionResult Delete(int id)
        {
            Note note = db.Notes.Find(id);
            if (note == null)
            {
                return NotFound();
            }
            NoteViewModel nvm = new NoteViewModel();
            nvm.Id = note.Id;
            nvm.Title = note.Title;
            nvm.Content = note.Content;
            return View(nvm);
        }
        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Delete(NoteViewModel model)
        {
            if (ModelState.IsValid)
            {
                Note note1 = db.Notes.FirstOrDefault(x => x.Id.Equals(model.Id));
                db.Notes.Remove(note1);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        public IActionResult Edit(int id)
        {
            Note note = db.Notes.Find(id);
            if (note == null)
            {
                return NotFound();
            }
            NoteViewModel nvm = new NoteViewModel();
            nvm.Id = note.Id;
            nvm.Title = note.Title;
            nvm.Content = note.Content;
            return View(nvm);
        }
        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Edit(NoteViewModel model)
        {
            if (ModelState.IsValid)
            {
                Note note1 = db.Notes.FirstOrDefault(x => x.Id.Equals(model.Id));
                note1.Content = model.Content;
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
    }
}

NotepadMVC/Views/Notes/Delete.cshtml
@model NoteViewModel
<form asp-controller="Notes" asp-action="Delete" method="post">
    <input type="hidden" asp-for="Id" />
    <span>@Model.Content this note will be delete, Do you approve?  </span>
    <button class="btn btn-primary">Yes, Delete</button>
</form>
<a asp-controller="Home" asp-action="Index"> Back to the Note page</a>

NotepadMVC/Views/Notes/Edit.cshtml
@model NoteViewModel

    <form asp-controller="Notes" asp-action="Edit" method="post">
        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label asp-for="Title"></label>
            <input asp-for="Title" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Content"></label>
            <textarea asp-for="Content" class="form-control" rows="10"></textarea>
        </div>
        <button class="btn btn-primary">Edit</button>
    </form>
    <a asp-controller="Home" asp-action="Index"> Back to the Note page</a>

NotepadMVC/Views/Notes/Yeni.cshtml
@model Note

<form method="post">
    <div class="form-group">
        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Content"></label>
        <textarea asp-for="Content" class="form-control"></textarea>
        <span asp-validation-for="Content" class="text-danger"></span>
    </div>
    <button class="btn btn-primary"> Add </button>
</form>